version: '3'
services:
  web:
    image: 127.0.0.1:5000/stackplat
    build: .
    environment:
      - MONGO_IP=192.168.0.2
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - dockernet
  redis:
    image: redis:alpine
networks:
    dockernet:
      external:
        name: dockernet